---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Gather Facts to check if a similar instance is running
      ec2_instance_facts:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: us-east-1
        filters:
          availability-zone: us-east-1
#          "tag:Name": "lb01"
      register: ec2_metadata

#- debug: msg="{{ ec2_metadata.instances }}"
