---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Provision Loadbalancer
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "{{ key_name }}"
        group: webserver
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        exact_count: 1
        region: "{{ region }}"
        count_tag:
            Name: lb01
        instance_tags:
            Name: lb01
      register: lb

    - name: Provision WebServer1
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "{{ key_name }}"
        group: webserver
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        exact_count: 1
        region: "{{ region }}"
        count_tag:
            Name: app01
        instance_tags:
            Name: app01
      register: app

    - name: Provision WebServer2
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "{{ key_name }}"
        group: webserver
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        exact_count: 1
        region: "{{ region }}"
        count_tag:
            Name: app02
        instance_tags:
            Name: app02
      register: app

    - name: Provision Database
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "{{ key_name }}"
        group: database
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        exact_count: 1
        region: "{{ region }}"
        count_tag:
            Name: db01
        instance_tags:
            Name: db01
      register: db

    - name: refresh_inventory
      meta: refresh_inventory

    - name: wait for ssh
      wait_for:
        port: 22
        host: "{{ item.public_ip }}"
        timeout: 300
        state: started
      with_items:
        - "{{ db.instances }}"
        - "{{ app.instances }}"
        - "{{ lb.instances }}"

- hosts: all
  become: true
  user: ubuntu
  gather_facts: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      tags: [ 'packages' ]

- include: database.yml
- include: webserver.yml
- include: loadbalancer.yml
