---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Provision Loadbalancer
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: ansible
        group: webserver
        instance_type: t2.micro
        image: ami-05a36d3b9aa4a17ac
        wait: true
        exact_count: 1
        region: us-east-1
        count_tag:
            Name: lb01
        instance_tags:
            Name: lb01
      register: loadbalancer

    - name: Provision WebServer1
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: ansible
        group: webserver
        instance_type: t2.micro
        image: ami-05a36d3b9aa4a17ac
        wait: true
        exact_count: 1
        region: us-east-1
        count_tag:
            Name: app01
        instance_tags:
            Name: app01
      register: WebServer1

    - name: Provision WebServer2
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: ansible
        group: webserver
        instance_type: t2.micro
        image: ami-05a36d3b9aa4a17ac
        wait: true
        exact_count: 1
        region: us-east-1
        count_tag:
            Name: app02
        instance_tags:
            Name: app02
      register: WebServer2

    - name: Provision Database
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: ansible
        group: database
        instance_type: t2.micro
        image: ami-05a36d3b9aa4a17ac
        wait: true
        exact_count: 1
        region: us-east-1
        count_tag:
            Name: db01
        instance_tags:
            Name: db01
      register: Database
