---
- hosts: cluster
  connection: "local"
  gather_facts: False
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        state: 'absent'
        instance_ids: "{{ ec2_id }}"
